version: '2.0'

services:

  app:
    image: biigle/app-dist:arm32v6
    user: ${USER_ID}:${GROUP_ID}
    restart: always
    depends_on:
      - cache
    tmpfs:
      - /var/www/storage/framework/views:uid=${USER_ID},gid=${GROUP_ID}
    volumes:
      - ./storage:/var/www/storage

  web:
    image: biigle/web-dist:arm32v6
    restart: always
    depends_on:
      - app
    volumes:
      - ./certificate:/etc/letsencrypt/live/example.com
      - ./storage:/var/www/storage
    ports:
      - 80:80
      - 443:443

  worker:
    image: biigle/worker-dist:arm32v6
    user: ${USER_ID}:${GROUP_ID}
    restart: always
    depends_on:
      - cache
    volumes_from:
      - app
    command: "php -d memory_limit=1G artisan queue:work --queue=high,default --sleep=5 --tries=3 --timeout=0"

  scheduler:
    image: biigle/worker-dist:arm32v6
    user: ${USER_ID}:${GROUP_ID}
    restart: always
    depends_on:
      - cache
    volumes_from:
      - app
    command: "/bin/sh -c 'trap exit SIGTERM; while sleep 60 & wait; do php -d memory_limit=1G artisan schedule:run >> /dev/null 2>&1; done'"

  database:
    image: arm32v6/postgres:10-alpine
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql
    environment:
      - "POSTGRES_DB=homestead"
      - "POSTGRES_USER=homestead"
      - "POSTGRES_PASSWORD=secret"

  cache:
    image: arm32v6/redis:3.2-alpine
    restart: always

volumes:
  dbdata:
