services:

  app:
    image: biigle/app-dist:arm64v8
    user: ${USER_ID}:${GROUP_ID}
    restart: always
    depends_on:
      - cache
    tmpfs:
      - /var/www/storage/framework/views:uid=${USER_ID},gid=${GROUP_ID}
    volumes:
      - ./storage:/var/www/storage

  web:
    image: biigle/web-dist:arm64v8
    restart: always
    depends_on:
      - app
    volumes:
      - ./certificate:/etc/letsencrypt/live/example.com
      - ./storage:/var/www/storage
    ports:
      - 80:80
      - 443:443 # Remove for a setup without SSL
    # Uncomment to use the webserver without SSL:
    # command: nginx -g 'daemon off;' -c /etc/nginx/nginx-no-ssl.conf

  worker:
    image: biigle/worker-dist:arm64v8
    user: ${USER_ID}:${GROUP_ID}
    restart: always
    depends_on:
      - cache
    volumes_from:
      - app
    init: true
    command: "php -d memory_limit=1G artisan queue:work --queue=high,default --sleep=5 --tries=3 --timeout=0"

  scheduler:
    image: biigle/worker-dist:arm64v8
    user: ${USER_ID}:${GROUP_ID}
    restart: always
    depends_on:
      - cache
    volumes_from:
      - app
    command: "/bin/sh -c 'trap exit TERM; while sleep 60 & wait; do php -d memory_limit=1G artisan schedule:run >> /dev/null 2>&1; done'"

  database:
    image: arm64v8/postgres:14-alpine
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=biigle"
      - "POSTGRES_USER=biigle"
      - "POSTGRES_PASSWORD=secret"

  cache:
    image: arm64v8/redis:7-alpine
    restart: always

volumes:
  dbdata:
