site_name: BIIGLE Admin Documentation
site_description: This is a collection of resources and documentation for maintainers of an instance of BIIGLE, the image and video annotation tool.
site_author: Martin Zurowietz
site_url: https://github.com/biigle/biigle/
repo_url: https://github.com/biigle/biigle/
edit_uri: blob/master/docs/
theme:
    name: readthedocs
    highlightjs: false
markdown_extensions:
    - toc:
        permalink: 
    - admonition:
nav:
  - Home: index.md
  - Installation: installation.md
  - Maintenance: maintenance.md
  - GPU computing: gpu.md
  - Synchronization: sync.md
  - Federated search: federated-search.md
  - Database schema: database-schema.md
  - Module development:
    - Module development: module-development/module-development.md
    - Advanced module development: module-development/advanced-module-development.md
    - Custom assets of modules: module-development/custom-assets.md
    - Mastering view mixins: module-development/view-mixins.md
  - Appendix:
    - GPU setup: appendix/gpu-setup.md
